### PR TITLE
Added new recipes with tests cases

### PR DESCRIPTION
**Pull request by Seniru**
New recipes
 - Celcius to Fahrenheit
 - Fahrenheit to Celcius
 - Kelvin to Celcius
 - Celcius to Kelvin

(Included tests cases for all)

### CODE REVIEW

**Comment by cesarferreira** [comment]
Thank you very much for the PR!

I just want to ask something, why the 2.7k lines for the package-lock.json?

We can get it merged after we fix this issue :)

**Comment by Seniru** [comment]
Thanks for your response :)

Well, IDK why there are 2.2k lines of additions in the package-lock.json file. I didn't change anything manually. 

I have no problem removing that. But I have a silly question: How can I remove those new additions without deleting the original file?

Thanks 😄

**Comment by cesarferreira** [comment]
Are you not using `yarn`? 

Oh, I see what happened, since I use `yarn` and you use `npm`, my package-lock.json was outdated, I'll accept it thanks

**Comment by Seniru** [comment]
Oh Ok 😁 Thanks for merging 👍

**Comment by cesarferreira** [comment]
bundled your update with a couple of mine on v1.1.0 https://github.com/cesarferreira/chef-cli/releases/tag/v1.1.0

**Pull request merged**
